name: CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        echo "Установка необходимых зависимостей"
        sudo apt-get update
        sudo apt-get install -y build-essential  # Установка необходимых для C инструментов

    - name: Compile the project
      run: |
        echo "Сборка проекта"
        gcc -o app app.c  # Компиляция вашего приложения

    - name: Run tests
      run: |
        echo "Запуск тестов"
        # Добавьте команду для проверки работы вашего приложения
        ./app  # Запускаем ваше приложение, чтобы проверить его работу

    - name: Deploy
      run: |
        echo "Деплой приложения"
        # Здесь вы можете добавить команды для деплоя, например:
        # scp app user@your-server:/path/to/deployment/ или вызов API для деплоя.
