name: Fist CI/CD pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  # Рекомендуется использование 'ubuntu-latest' для C-программ

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment #   Установка необходимых для C инструментов
      run: |
        echo "Установка необходимых зависимостей"
        sudo apt-get update
        sudo apt-get install -y build-essential  
     

    - name: Compile the project # Компиляция моего приложения
      run: |
        echo "Сборка проекта"
        gcc -o app app.c  

    - name: Run tests # Запускаем наше приложение, чтобы проверить его работу
      run: |
        echo "Запуск тестов"
        ./app  
    - name: Deploy  # В первом учебном pipeline Deploy не выполняется, формат шаблона сохранен
      run: |
        echo "Деплой приложения"
       
