name: First pipeline

on:
  pull_request:
    branches: [ master ]

job: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - run: npm cli
      - run: npm test
      - run: npm run build
